/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "basilica-cistern": {
    "base": "basilica-cistern",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "blue-mosque": {
    "base": "blue-mosque",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "bosphorus": {
    "base": "bosphorus",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "city-highlights": {
    "base": "city-highlights",
    "width": 1920,
    "height": 194,
    "fallbackWidth": 800,
    "fallbackHeight": 81,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1229,
    "height": 922,
    "fallbackWidth": 1229,
    "fallbackHeight": 922,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "europe-asia": {
    "base": "europe-asia",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1920,
    "height": 1884,
    "fallbackWidth": 800,
    "fallbackHeight": 785,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "grand-bazaar": {
    "base": "grand-bazaar",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hagia-sophia": {
    "base": "hagia-sophia",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 1920,
    "fallbackHeight": 1080,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "highlights": {
    "base": "highlights",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 1920,
    "fallbackHeight": 1080,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 1920,
    "fallbackHeight": 1080,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "spice-bazaar": {
    "base": "spice-bazaar",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "topkapi-palace": {
    "base": "topkapi-palace",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 1920,
    "height": 1264,
    "fallbackWidth": 800,
    "fallbackHeight": 527,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
